management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
  endpoint:
    health:
      show-components: always
      show-details: always

server:
  port: 8002
  error:
    path: /error
spring:
  application:
    name: service-b
  main:
    banner-mode: 'off'
    log-startup-info: true
  redis:
    enable: true
    type: 0
    schema: redis
    database: 0
    host: 127.0.0.1
    port: 6379
    cluster:
      nodes: >-
        10.0.4.110:6371,10.0.4.110:6372,10.0.4.110:6373,10.0.4.111:6371,10.0.4.111:6372,10.0.4.111:6373
  session:
    store-type: redis
    timeout: 30m
  datasource:
    enable: true
    url: jdbc:mysql://127.0.0.1:3306/security?useSSL=false
    username: root
    password:
    beetlsql:
      worker.id: 1
      data.center.id: 2

request:
  pre: true
  after: true
  error: true
